In [1]:
# load libraries and data

In [2]:
import numpy as np
import statsmodels.api as sm

In [3]:
spector_data = sm.datasets.spector.load()

In [8]:
spector_data.exog

array([[ 2.66, 20.  ,  0.  ],
       [ 2.89, 22.  ,  0.  ],
       [ 3.28, 24.  ,  0.  ],
       [ 2.92, 12.  ,  0.  ],
       [ 4.  , 21.  ,  0.  ],
       [ 2.86, 17.  ,  0.  ],
       [ 2.76, 17.  ,  0.  ],
       [ 2.87, 21.  ,  0.  ],
       [ 3.03, 25.  ,  0.  ],
       [ 3.92, 29.  ,  0.  ],
       [ 2.63, 20.  ,  0.  ],
       [ 3.32, 23.  ,  0.  ],
       [ 3.57, 23.  ,  0.  ],
       [ 3.26, 25.  ,  0.  ],
       [ 3.53, 26.  ,  0.  ],
       [ 2.74, 19.  ,  0.  ],
       [ 2.75, 25.  ,  0.  ],
       [ 2.83, 19.  ,  0.  ],
       [ 3.12, 23.  ,  1.  ],
       [ 3.16, 25.  ,  1.  ],
       [ 2.06, 22.  ,  1.  ],
       [ 3.62, 28.  ,  1.  ],
       [ 2.89, 14.  ,  1.  ],
       [ 3.51, 26.  ,  1.  ],
       [ 3.54, 24.  ,  1.  ],
       [ 2.83, 27.  ,  1.  ],
       [ 3.39, 17.  ,  1.  ],
       [ 2.67, 24.  ,  1.  ],
       [ 3.65, 21.  ,  1.  ],
       [ 4.  , 23.  ,  1.  ],
       [ 3.1 , 21.  ,  1.  ],
       [ 2.39, 19.  ,  1.  ]])

In [9]:
spector_data.exog = sm.add_constant(spector_data.exog, prepend = False)

In [10]:
spector_data.exog

array([[ 2.66, 20.  ,  0.  ,  1.  ],
       [ 2.89, 22.  ,  0.  ,  1.  ],
       [ 3.28, 24.  ,  0.  ,  1.  ],
       [ 2.92, 12.  ,  0.  ,  1.  ],
       [ 4.  , 21.  ,  0.  ,  1.  ],
       [ 2.86, 17.  ,  0.  ,  1.  ],
       [ 2.76, 17.  ,  0.  ,  1.  ],
       [ 2.87, 21.  ,  0.  ,  1.  ],
       [ 3.03, 25.  ,  0.  ,  1.  ],
       [ 3.92, 29.  ,  0.  ,  1.  ],
       [ 2.63, 20.  ,  0.  ,  1.  ],
       [ 3.32, 23.  ,  0.  ,  1.  ],
       [ 3.57, 23.  ,  0.  ,  1.  ],
       [ 3.26, 25.  ,  0.  ,  1.  ],
       [ 3.53, 26.  ,  0.  ,  1.  ],
       [ 2.74, 19.  ,  0.  ,  1.  ],
       [ 2.75, 25.  ,  0.  ,  1.  ],
       [ 2.83, 19.  ,  0.  ,  1.  ],
       [ 3.12, 23.  ,  1.  ,  1.  ],
       [ 3.16, 25.  ,  1.  ,  1.  ],
       [ 2.06, 22.  ,  1.  ,  1.  ],
       [ 3.62, 28.  ,  1.  ,  1.  ],
       [ 2.89, 14.  ,  1.  ,  1.  ],
       [ 3.51, 26.  ,  1.  ,  1.  ],
       [ 3.54, 24.  ,  1.  ,  1.  ],
       [ 2.83, 27.  ,  1.  ,  1.  ],
       [ 3.39, 17.  ,  1.  ,  1.  ],
 

In [12]:
spector_data.endog

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 1., 0., 0., 0., 1., 0., 0., 0.,
       0., 0., 1., 0., 1., 0., 0., 1., 1., 1., 0., 1., 1., 0., 1.])

In [11]:
# fit model

In [13]:
mod = sm.OLS(spector_data.endog, spector_data.exog)

In [14]:
res = mod.fit()

In [15]:
print(res.summary())

                            OLS Regression Results                            
Dep. Variable:                      y   R-squared:                       0.416
Model:                            OLS   Adj. R-squared:                  0.353
Method:                 Least Squares   F-statistic:                     6.646
Date:                Thu, 14 Feb 2019   Prob (F-statistic):            0.00157
Time:                        10:34:11   Log-Likelihood:                -12.978
No. Observations:                  32   AIC:                             33.96
Df Residuals:                      28   BIC:                             39.82
Df Model:                           3                                         
Covariance Type:            nonrobust                                         
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
x1             0.4639      0.162      2.864      0.0

In [16]:
# https://www.statsmodels.org/stable/regression.html